# Generated by Django 5.2 on 2025-04-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=255)),
                ('resume_link', models.URLField()),
                ('linkedin_link', models.URLField()),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
